ablrdemo/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from django.conf import settings
from myinfo import urls as myinfo_urls
from myinfo import views as myinfo_views
from django.shortcuts import redirect


urlpatterns = [
    path('', lambda req: redirect('myinfo:contact')),
    path('admin/', admin.site.urls),
    path('myinfo/', include(myinfo_urls)),
    path('login', myinfo_views.login_view, name='login'),
    path('callback', myinfo_views.auth_callback, name='auth-callback'),
]

myinfo/urls.py
from django.urls import path
from . import views as myinfo_views

app_name = 'myinfo'

urlpatterns = [
    path('contact', myinfo_views.contact, name='contact'),
    path('income', myinfo_views.income, name='income'),
    path('personal', myinfo_views.personal, name='personal'),
    path('other', myinfo_views.other, name='other'),
]

myinfo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class UserProfile(models.Model):
    user = models.OneToOneField(User,
        related_name='profile',
        on_delete=models.CASCADE)

    uinfin = models.CharField(max_length=9, blank=True)
    sex  = models.CharField(max_length=6, blank=True)
    race = models.CharField(max_length=15, blank=True)
    nationality  = models.CharField(max_length=15, blank=True)
    dob  = models.DateField(blank=True, null=True)
    mobile  = models.CharField(max_length=15, blank=True)
    housetype = models.CharField(max_length=15, blank=True)
    address_block = models.CharField(max_length=10, blank=True)
    address_street = models.CharField(max_length=100, blank=True)
    address_building = models.CharField(max_length=100, blank=True)
    address_floor = models.CharField(max_length=5, blank=True)
    address_unit = models.CharField(max_length=5, blank=True)
    postal = models.CharField(max_length=10, blank=True)


@receiver(post_save, sender=User)
def create_or_update_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.profile.save()

myinfo/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .models import UserProfile
from django.urls import reverse
from django.core.serializers.json import DjangoJSONEncoder
import json
from myinfo.client import MyInfoClient
from django.contrib.auth.decorators import login_required


def login_view(request):
    url = MyInfoClient.get_authorise_url(state="blahblah", callback_url=request.build_absolute_uri(reverse('auth-callback')))
    return redirect(url)

def auth_callback(request):
    user = authenticate(code=request.GET['code'])
    if user:
        login(request, user)
    return redirect('myinfo:contact')


@login_required
def income(request):
    return render(request, 'myinfo/income.html')

@login_required
def contact(request):
    profile_data = UserProfile.objects.filter(user=request.user).values()[0]
    context = {
        "contact_info": json.dumps({
            "email": request.user.email,
            **profile_data
        }, cls=DjangoJSONEncoder)
    }
    return render(request, 'myinfo/contact.html', context)


@login_required
def personal(request):
    profile_data = UserProfile.objects.filter(user=request.user).values()[0]
    context = {
        "personal_info": json.dumps({
            "name": request.user.first_name,
            **profile_data
        }, cls=DjangoJSONEncoder)
    }

    return render(request, 'myinfo/personal.html', context)


@login_required
def other(request):
    return render(request, 'myinfo/other.html')

myinfo/templates/myinfo/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  {% block body %}
  {% block heading %}
  <div class='heading' id='heading'>
    <h1>My Info</h1>
  </div>
  {% endblock heading %}
  {% block menu %}
  <div class='menu' id='menu'>
    <a href="{% url "myinfo:contact" %}">Contact Info</a>
    <a href="{% url "myinfo:personal" %}">Personal Info</a>
    <a href="{% url "myinfo:income" %}">Income Info</a>
    <a href="{% url "myinfo:other" %}">Other Info</a>
  </div>
  {% endblock menu %}
  {% block content %}
  <div id='main'></div>
  {% endblock content %}
  {% endblock body %}
  <script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
  <script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
  {% block script %}{% endblock script %}
</body>
</html>

myinfo/templates/myinfo/contact.html
{% extends "myinfo/base.html" %}

{% load static %}
{% block script %}
<script>
  window.initialData = {{ contact_info|safe }};
</script>
<script src="{% static "js/contact-info.js" %}" ></script>
{% endblock script %}

myinfo/templates/myinfo/income.html
{% extends "myinfo/base.html" %}

{% load static %}
{% block script %}
<script src="{% static "js/income-info.js" %}"></script>
{% endblock script %}

myinfo/templates/myinfo/other.html
{% extends "myinfo/base.html" %}

{% load static %}

{% block content %}
<p>Not Implemented Yet</p>
{% endblock content %}

myinfo/templates/myinfo/personal.html
{% extends "myinfo/base.html" %}

{% load static %}

{% block script %}
<script>
	window.initialData = {{ personal_info|safe }};
</script>
<script src="{% static "js/personal-info.js" %}" ></script>
{% endblock script %}